/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Name } from "./Name";
import { NameCountArgs } from "./NameCountArgs";
import { NameFindManyArgs } from "./NameFindManyArgs";
import { NameFindUniqueArgs } from "./NameFindUniqueArgs";
import { DeleteNameArgs } from "./DeleteNameArgs";
import { NameService } from "../name.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Name)
export class NameResolverBase {
  constructor(
    protected readonly service: NameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Name",
    action: "read",
    possession: "any",
  })
  async _namesMeta(
    @graphql.Args() args: NameCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Name])
  @nestAccessControl.UseRoles({
    resource: "Name",
    action: "read",
    possession: "any",
  })
  async names(@graphql.Args() args: NameFindManyArgs): Promise<Name[]> {
    return this.service.names(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Name, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Name",
    action: "read",
    possession: "own",
  })
  async name(@graphql.Args() args: NameFindUniqueArgs): Promise<Name | null> {
    const result = await this.service.name(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Name)
  @nestAccessControl.UseRoles({
    resource: "Name",
    action: "delete",
    possession: "any",
  })
  async deleteName(@graphql.Args() args: DeleteNameArgs): Promise<Name | null> {
    try {
      return await this.service.deleteName(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
