/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TestimonialsService } from "../testimonials.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TestimonialsCreateInput } from "./TestimonialsCreateInput";
import { Testimonials } from "./Testimonials";
import { TestimonialsFindManyArgs } from "./TestimonialsFindManyArgs";
import { TestimonialsWhereUniqueInput } from "./TestimonialsWhereUniqueInput";
import { TestimonialsUpdateInput } from "./TestimonialsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TestimonialsControllerBase {
  constructor(
    protected readonly service: TestimonialsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Testimonials })
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTestimonials(
    @common.Body() data: TestimonialsCreateInput
  ): Promise<Testimonials> {
    return await this.service.createTestimonials({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        feedback: true,
        date: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Testimonials] })
  @ApiNestedQuery(TestimonialsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async testimonialsItems(
    @common.Req() request: Request
  ): Promise<Testimonials[]> {
    const args = plainToClass(TestimonialsFindManyArgs, request.query);
    return this.service.testimonialsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        feedback: true,
        date: true,
        name: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Testimonials })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async testimonials(
    @common.Param() params: TestimonialsWhereUniqueInput
  ): Promise<Testimonials | null> {
    const result = await this.service.testimonials({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        feedback: true,
        date: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Testimonials })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTestimonials(
    @common.Param() params: TestimonialsWhereUniqueInput,
    @common.Body() data: TestimonialsUpdateInput
  ): Promise<Testimonials | null> {
    try {
      return await this.service.updateTestimonials({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          feedback: true,
          date: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Testimonials })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTestimonials(
    @common.Param() params: TestimonialsWhereUniqueInput
  ): Promise<Testimonials | null> {
    try {
      return await this.service.deleteTestimonials({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          feedback: true,
          date: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
