/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Testimonials } from "./Testimonials";
import { TestimonialsCountArgs } from "./TestimonialsCountArgs";
import { TestimonialsFindManyArgs } from "./TestimonialsFindManyArgs";
import { TestimonialsFindUniqueArgs } from "./TestimonialsFindUniqueArgs";
import { CreateTestimonialsArgs } from "./CreateTestimonialsArgs";
import { UpdateTestimonialsArgs } from "./UpdateTestimonialsArgs";
import { DeleteTestimonialsArgs } from "./DeleteTestimonialsArgs";
import { TestimonialsService } from "../testimonials.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Testimonials)
export class TestimonialsResolverBase {
  constructor(
    protected readonly service: TestimonialsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "read",
    possession: "any",
  })
  async _testimonialsItemsMeta(
    @graphql.Args() args: TestimonialsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Testimonials])
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "read",
    possession: "any",
  })
  async testimonialsItems(
    @graphql.Args() args: TestimonialsFindManyArgs
  ): Promise<Testimonials[]> {
    return this.service.testimonialsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Testimonials, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "read",
    possession: "own",
  })
  async testimonials(
    @graphql.Args() args: TestimonialsFindUniqueArgs
  ): Promise<Testimonials | null> {
    const result = await this.service.testimonials(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Testimonials)
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "create",
    possession: "any",
  })
  async createTestimonials(
    @graphql.Args() args: CreateTestimonialsArgs
  ): Promise<Testimonials> {
    return await this.service.createTestimonials({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Testimonials)
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "update",
    possession: "any",
  })
  async updateTestimonials(
    @graphql.Args() args: UpdateTestimonialsArgs
  ): Promise<Testimonials | null> {
    try {
      return await this.service.updateTestimonials({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Testimonials)
  @nestAccessControl.UseRoles({
    resource: "Testimonials",
    action: "delete",
    possession: "any",
  })
  async deleteTestimonials(
    @graphql.Args() args: DeleteTestimonialsArgs
  ): Promise<Testimonials | null> {
    try {
      return await this.service.deleteTestimonials(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
